-sverilog $LAB_PATH/RTL/SGDMAC_FIFO.sv
-sverilog $LAB_PATH/RTL/SGDMAC_TOP.sv
-sverilog $LAB_PATH/RTL/SGDMAC_CFG.sv
-sverilog $LAB_PATH/RTL/SGDMAC_ARBITER.sv
-sverilog $LAB_PATH/RTL/SGDMAC_READ.sv
-sverilog $LAB_PATH/RTL/SGDMAC_WRITE.sv
-sverilog $LAB_PATH/RTL/SGDMAC_DESCRIPTOR_FETCHER.sv


